"""
Unit tests for uw_copilot.feedback.FeedbackManager

Tests validate the SQL generated by record() and the return contract,
without hitting a real warehouse. val() and esc() are local functions
inside record(), so we test their effects via the produced SQL string.
"""
import re
import pytest
from unittest.mock import MagicMock


# ─── Shared fixtures ──────────────────────────────────────────────────────────

def _make_config(warehouse_id="test-wh-001"):
    cfg = MagicMock()
    cfg.warehouse_id = warehouse_id
    cfg.catalog      = "atlas"
    cfg.schema       = "atlas_insurance_rag"
    return cfg


def _make_client(succeed: bool = True):
    """Stub WorkspaceClient whose execute_statement simulates SUCCEEDED or FAILED."""
    w = MagicMock()
    status = MagicMock()
    status.state.value = "SUCCEEDED" if succeed else "FAILED"
    if not succeed:
        status.error.message = "Simulated warehouse failure"
    result = MagicMock()
    result.status   = status
    result.manifest = None   # DML returns no manifest
    w.statement_execution.execute_statement.return_value = result
    return w


def _get_sql(succeed=True, **kwargs) -> str:
    """Call record() with given kwargs and return the SQL that was executed."""
    from uw_copilot.feedback import FeedbackManager
    w   = _make_client(succeed=succeed)
    fm  = FeedbackManager(_make_config(), w)
    defaults = dict(
        user_id="test_user", query="What is the loss ratio?",
        response="The loss ratio is 82%.", rating="thumbs_down",
        session_id="sess-abc-123",
    )
    defaults.update(kwargs)
    fm.record(**defaults)
    call = w.statement_execution.execute_statement.call_args
    return call[1]["statement"] if call[1] else call[0][0]


# ─── val() — tested through the produced SQL ─────────────────────────────────

class TestValBehaviourViaSQL:
    def test_none_session_id_produces_null(self):
        sql = _get_sql(session_id=None)
        assert "NULL," in sql

    def test_empty_session_id_produces_quoted_empty(self):
        # Empty string is not None — must be quoted as '' not NULL.
        # NOTE: comment defaults to None → produces NULL, elsewhere in the SQL,
        # so we only check that the quoted empty string appears at all.
        sql = _get_sql(session_id="")
        assert "''," in sql   # '' must appear (session_id is quoted empty, not NULL)

    def test_session_id_is_quoted(self):
        sql = _get_sql(session_id="my-session-123")
        assert "'my-session-123'" in sql

    def test_single_quote_in_query_is_escaped(self):
        sql = _get_sql(query="What's the fleet size?")
        # The apostrophe must be escaped as '' — not left raw (SQL injection guard)
        assert "What''" in sql

    def test_single_quote_in_response_is_escaped(self):
        sql = _get_sql(response="O'Brien Logistics has 42 trucks.")
        assert "O''" in sql


# ─── Rating int conversion ────────────────────────────────────────────────────

class TestRatingInt:
    def test_thumbs_up_produces_1(self):
        sql = _get_sql(rating="thumbs_up")
        # rating_int appears on its own line: "                1,"
        assert re.search(r"\b1,\s*\n", sql), f"Expected '1,' line not found:\n{sql}"

    def test_thumbs_down_produces_minus_1(self):
        sql = _get_sql(rating="thumbs_down")
        assert re.search(r"-1,\s*\n", sql), f"Expected '-1,' line not found:\n{sql}"

    def test_unknown_rating_defaults_to_minus_1(self):
        sql = _get_sql(rating="ambiguous")
        assert re.search(r"-1,\s*\n", sql)


# ─── INSERT SQL structure ─────────────────────────────────────────────────────

class TestInsertStructure:
    def test_targets_correct_table(self):
        sql = _get_sql()
        assert "copilot_feedback" in sql

    def test_all_required_columns_present(self):
        sql = _get_sql()
        for col in ("feedback_id", "session_id", "user_id", "question", "answer", "rating", "created_at"):
            assert col in sql, f"Column {col!r} missing from INSERT SQL"

    def test_feedback_id_is_uuid_shaped(self):
        sql = _get_sql()
        # feedback_id is a UUID in the SQL literal
        uuid_pattern = r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
        assert re.search(uuid_pattern, sql), "No UUID-shaped feedback_id found in SQL"

    def test_timestamp_keyword_present(self):
        sql = _get_sql()
        assert "TIMESTAMP" in sql


# ─── return contract ─────────────────────────────────────────────────────────

class TestReturnContract:
    def test_returns_uuid_on_success(self):
        from uw_copilot.feedback import FeedbackManager
        fm  = FeedbackManager(_make_config(), _make_client(succeed=True))
        fid = fm.record(user_id="u", query="q", response="r",
                        rating="thumbs_up", session_id="s")
        assert fid is not None
        assert re.match(r"[0-9a-f\-]{36}", str(fid))

    def test_returns_none_on_warehouse_failure(self):
        from uw_copilot.feedback import FeedbackManager
        fm  = FeedbackManager(_make_config(), _make_client(succeed=False))
        result = fm.record(user_id="u", query="q", response="r",
                           rating="thumbs_down", session_id="s")
        assert result is None

    def test_returns_none_when_no_warehouse_id(self):
        from uw_copilot.feedback import FeedbackManager
        cfg = _make_config(warehouse_id=None)
        fm  = FeedbackManager(cfg, MagicMock())
        result = fm.record(user_id="u", query="q", response="r",
                           rating="thumbs_up", session_id="s")
        assert result is None
